### PR TITLE
Uneject

### PR DESCRIPTION
**Pull request by ismay**
Todo

- [x] .github folder
- [x] cli-style
- [x] put back src files
- [x] public folder
- [x] i18n folder
- [x] check package.json (remove unused dependencies)
- [x] enable tests
- [ ] troubleshoot errors when running app
- [ ] dotfiles
- [ ] .env files for api discovery
- [ ] working bundling
- [ ] config folder
- [ ] scripts folder
- [ ] enable travis (and cli-style)
- [ ] update readme
- [ ] move to static manifest.json (remove d2-manifest)
- [ ] check the scripts in package.json, make sure all are still used
- [ ] check publish-build and deploy-build tasks (is one no longer necessary?) and secure tokens in travis.yml.
- [ ] port CSS to CSS Modules

Verify

- [ ] is it ok to no longer run the `npm run extract-pot` task automatically before `npm run localize`? Can we remove it and its dependencies?
- [ ] ensure updated snapshots are correct

### CODE REVIEW

**Comment by varl** [comment]
Based on the decision about what CSS solution to use: https://github.com/dhis2/notes/blob/master/decisions/2019/12/18-feds-test-location-attrs-css.md#what-to-use-for-css-styling-in-appscomponents-79

We should port the styled-jsx CSS to CSS Modules in the unejection-phase.

**Comment by HendrikThePendric** [comment]
@ismay I hope you don't mind me closing this PR. The following is the case:
- CRA doesn't support styled-jsx, but our app-platform does
- Because we had lots of calls to `i18n.t` directly from JavaScript modules (i.e. config files), these strings were always being translated to the default locale (`en`)
- The easiest way to fix this problem was to port the app to the app-platform (see #144). And the bonus was that this worked fine with styled-jsx, so we didn't have to refactor to CSS modules straight away.

Refactoring to CSS Modules is still something we need to do at some point, but I've opened issue #145 to remind us about that.

If I remember correctly, the main point of "unejecting" our apps was to make it easier to port them to the app-platform later on. Since this port has already been done, I would say this PR has been superseded by #144 and I am closing this one.

**Comment by HendrikThePendric** [comment]
@ismay I hope you don't mind me closing this PR. The following is the case:
- CRA doesn't support styled-jsx, but our app-platform does
- Because we had lots of calls to `i18n.t` directly from JavaScript modules (i.e. config files), these strings were always being translated to the default locale (`en`)
- The easiest way to fix this problem was to port the app to the app-platform (see #144). And the bonus was that this worked fine with styled-jsx, so we didn't have to refactor to CSS modules straight away.

Refactoring to CSS Modules is still something we need to do at some point, but I've opened issue #145 to remind us about that.

If I remember correctly, the main point of "unejecting" our apps was to make it easier to port them to the app-platform later on. Since this port has already been done, I would say this PR has been superseded by #144 and I am closing this one.

**Comment by ismay** [comment]
> @ismay I hope you don't mind me closing this PR. The following is the case:
> 
>     * CRA doesn't support styled-jsx, but our app-platform does
> 
>     * Because we had lots of calls to `i18n.t` directly from JavaScript modules (i.e. config files), these strings were always being translated to the default locale (`en`)
> 
>     * The easiest way to fix this problem was to port the app to the app-platform (see #144). And the bonus was that this worked fine with styled-jsx, so we didn't have to refactor to CSS modules straight away.
> 
> 
> Refactoring to CSS Modules is still something we need to do at some point, but I've opened issue #145 to remind us about that.
> 
> If I remember correctly, the main point of "unejecting" our apps was to make it easier to port them to the app-platform later on. Since this port has already been done, I would say this PR has been superseded by #144 and I am closing this one.

Ah, a blast from the past. Well, it's always sad to see a PR go unmerged, but I think after a bit of time to myself I'll be able to cope with it 😋👍.

**Pull request closed without merging**
