### PR TITLE
chore: upgrade headerbar to the latest and greatest

### PR DESCRIPTION
**Pull request by varl**

### CODE REVIEW

**Comment by varl** [comment]
The build fails because this is an ejected application. We need to run Babel on the @dhis2 dependencies.

The Cucumber/Webdriver setup is poorly maintained and does not support the current Node LTS (12), so I'm dropping those deps to be able to build.

This app needs some love:

- Convert to app-platform (secondary option: unject to new CRA)
- Convert e2e tests to Cypress

**Comment by varl** [comment]
Tested in a local instance.

**Comment by HendrikThePendric** [comment]
> This app needs some love:
> 
> * Convert to app-platform (secondary option: unject to new CRA)
> * Convert e2e tests to Cypress

@varl Shall I create JIRA issues for this?

**Comment by varl** [comment]
> > This app needs some love:
> > 
> > * Convert to app-platform (secondary option: unject to new CRA)
> > * Convert e2e tests to Cypress
> 
> @varl Shall I create JIRA issues for this?

No, don't worry about it. I'll create them as part of some other epics I'm outlining.

**Comment by varl** [comment]
Thanks for helping out with the review!

**Pull request merged**
